# Generated by Django 4.1.5 on 2023-01-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteNamePersian', models.CharField(max_length=40)),
                ('logo', models.ImageField(upload_to='images/logo')),
                ('siteNameEnglish', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'اطلاعات سایت',
                'verbose_name_plural': 'اطلاعات سایت',
            },
        ),
    ]
