# Generated by Django 4.1.5 on 2023-01-14 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='logo',
            field=models.ImageField(upload_to='images/logo', verbose_name='لوگو سایت'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='siteNameEnglish',
            field=models.CharField(max_length=40, verbose_name='اسم سایت انگلیسی'),
        ),
        migrations.AlterField(
            model_name='siteinformation',
            name='siteNamePersian',
            field=models.CharField(max_length=40, verbose_name='اسم سایت فارسی'),
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('caption', models.TextField()),
                ('image', models.ImageField(upload_to='post/')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('Categories', models.ManyToManyField(to='home.categories')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
            },
        ),
    ]
