# Generated by Django 4.1.5 on 2023-01-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_categories_alter_siteinformation_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
