# Generated by Django 4.1.5 on 2023-01-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_posts_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='hot',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='categories',
            name='title',
            field=models.CharField(max_length=20, verbose_name='اسم دسته بندی'),
        ),
    ]
