# Generated by Django 4.1.5 on 2023-01-26 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_siteinformation_email_siteinformation_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinformation',
            name='siteNamePersian',
            field=models.CharField(max_length=20, verbose_name='اسم سایت به فارسی'),
        ),
    ]
