# Generated by Django 4.1.7 on 2023-03-22 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_siteinformation_sitenamepersian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='published',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
